In [46]:
### Data Preprocessing
import pandas as pd

# Combine CSVs
csv1 = pd.read_csv("Test.csv")
csv2 = pd.read_csv("Customers.csv")

dataframe = pd.concat( [csv1, csv2], ignore_index = True )
dataframe = dataframe.drop(["ID", "Segmentation", "Var_1"] , axis = 1)

# Handle blanks in  Married, Graduated, Profession, work, fam size => I will delete the rows with NaN values
dataframe = dataframe.dropna() # delete rows with NaN values

# Store Professions
professions = set()
for value in dataframe["Profession"]:
  professions.add(value)

# Adjust the necessary columns 
for i in dataframe.index:

  # Change professions to binary columns
  profession = dataframe["Profession"][i]
  if profession == 'Lawyer':
    dataframe.loc[i, "Lawyer"] = 1
  else: 
    dataframe.loc[i, "Lawyer"] = 0

  if profession == 'Homemaker':
    dataframe.loc[i, "Homemaker"] = 1
  else: 
    dataframe.loc[i, "Homemaker"] = 0

  if profession == 'Entertainment':
    dataframe.loc[i, "Entertainment"] = 1
  else: 
    dataframe.loc[i, "Entertainment"] = 0

  if profession == 'Doctor':
    dataframe.loc[i, "Doctor"] = 1
  else: 
    dataframe.loc[i, "Doctor"] = 0

  if profession == 'Engineer':
    dataframe.loc[i, "Engineer"] = 1
  else: 
    dataframe.loc[i, "Engineer"] = 0

  if profession == 'Healthcare':
    dataframe.loc[i, "Healthcare"] = 1
  else: 
    dataframe.loc[i, "Healthcare"] = 0

  if profession == 'Artist':
    dataframe.loc[i, "Artist"] = 1
  else: 
    dataframe.loc[i, "Artist"] = 0

  if profession == 'Marketing':
    dataframe.loc[i, "Marketing"] = 1
  else: 
    dataframe.loc[i, "Marketing"] = 0

  if profession == 'Executive':
    dataframe.loc[i, "Executive"] = 1
  else: 
    dataframe.loc[i, "Executive"] = 0
  

  # Change Gender to 2 new columns Female and Male
  gender = dataframe["Gender"][i]
  if gender == "Female": 
    dataframe.loc[i, "Female"] = 1 
    dataframe.loc[i, "Male"] = 0 

  if gender == "Male": 
    dataframe.loc[i, "Female"] = 0
    dataframe.loc[i, "Male"] = 1

  # Change Ever_Married, Graduated to 0 and 1
  married = dataframe["Ever_Married"][i] 
  graduated = dataframe["Graduated"][i] 
  if married == "Yes": 
    dataframe.loc[i, "Ever_Married"] = 1
  else: 
    dataframe.loc[i, "Ever_Married"] = 0

  if married == "Yes": 
    dataframe.loc[i, "Graduated"] = 1
  else: 
    dataframe.loc[i, "Graduated"] = 0

dataframe = dataframe.drop("Gender", axis = 1)
dataframe = dataframe.drop("Profession", axis = 1)


# Separate Data
features = dataframe.drop(["Spending_Score"], axis = 1)
label = dataframe["Spending_Score"]
print(f"Featurs: {len(features)}, Label: {len(label)}")
features

Featurs: 8896, Label: 8896

,Ever_Married,Age,Graduated,Work_Experience,Family_Size,Lawyer,Homemaker,Entertainment,Doctor,Engineer,Healthcare,Artist,Marketing,Executive,Female,Male
0,1,36,1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,37,1,8.0,4.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,1,59,1,11.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
5,1,47,1,0.0,5.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6,1,61,1,5.0,3.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10689,1,41,1,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
10691,0,35,0,3.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
10692,0,33,0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
10693,0,27,0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
10694,1,37,1,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0

In [47]:
# Split Data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features.values, label.values, test_size = 0.2)

# Apply Feature Scaling
from sklearn.preprocessing import StandardScaler
feature_scaler = StandardScaler()
X_train = feature_scaler.fit_transform(X_train)
X_test = feature_scaler.transform(X_test)

In [48]:
### K-Nearest Neighbor Classifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

knn = KNeighborsClassifier( n_neighbors = 100)
knn.fit(X_train, y_train)
KNN_prediction = knn.predict(X_test)
KNN_score = accuracy_score(y_test, KNN_prediction)

In [49]:
### Build Logistic Regression
from sklearn.linear_model import LogisticRegression
logistic_classifier = LogisticRegression()
logistic_classifier.fit(X_train, y_train)
logistic_prediction = logistic_classifier.predict(X_test)
logistic_score = accuracy_score(y_test, logistic_prediction)
logistic_prediction

array(['Average', 'High', 'Low', ..., 'Average', 'Average', 'High'],
      dtype=object)

In [50]:
### Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier()
tree.fit(X_train, y_train)
tree_predication = tree.predict(X_test)
tree_score = accuracy_score(y_test, tree_predication)

In [51]:
### Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier( n_estimators = 100 )
forest.fit(X_train, y_train)
forest_prediction = forest.predict(X_test)
forest_score = accuracy_score(y_test, forest_prediction)

In [52]:
### Support Vector Machine
from sklearn.svm import SVC
svc = SVC(kernel = "linear")
svc.fit(X_train, y_train)
svc_prediction = svc.predict(X_test)
svc_score = accuracy_score(y_test, svc_prediction)

In [53]:
### Kernel Support Vector Machine
kernel_svc = SVC(kernel = "rbf")
kernel_svc.fit(X_train, y_train)
kernel_svc_prediction = kernel_svc.predict(X_test)
kernel_svc_score = accuracy_score(y_test, kernel_svc_prediction)

In [54]:
### Naive Bayes Model
from sklearn.naive_bayes import GaussianNB
bayes = GaussianNB()
bayes.fit(X_train, y_train)
bayes_prediction = bayes.predict(X_test)
bayes_score = accuracy_score(y_test, bayes_prediction)

In [55]:
### Evaluate Models

print(f"K-Nearest Neighbors Score: {KNN_score}")
print(f"Logistic Regression Score: {logistic_score}")
print(f"Decision Tree Score: {tree_score}")
print(f"Random Forest Score: {forest_score}")
print(f"Support Vector Machine Score: {svc_score}")
print(f"Kernel Support Vector Machine Score: {kernel_svc_score}")
print(f"Bayes Model Score: {bayes_score}")

K-Nearest Neighbors Score: 0.7898876404494382
Logistic Regression Score: 0.8056179775280898
Decision Tree Score: 0.7764044943820225
Random Forest Score: 0.7955056179775281
Support Vector Machine Score: 0.801123595505618
Kernel Support Vector Machine Score: 0.8151685393258427
Bayes Model Score: 0.7438202247191011